### ISSUE TITLE
PlotSquired Support.

### ISSUE THREAD

**Issue by TMCThomas** [licks92/WirelessRedstone#123]
Hi, is it may possible to support PlotSquired? It's for some reason not working, Altrough i don't think the problem lies within Wireless-Redstone it would be awesome if you could support it ;D

Best Regards Thomas Mulder

**Comment by Bart-0110** [comment]
What is not working?

**Comment by TMCThomas** [comment]
I can create a sign perfectly fine. But when i try to power the transmitter Nothing happens to the receiver. Everything worked fine with plotme. Since thats abandoned is was forced to use plotsquired instead.

**Comment by Bart-0110** [comment]
Do you have any errors?

**Comment by TMCThomas** [comment]
yes, after that the servers has booted up, when the first player joins i've got this error:
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: java.lang.NumberFormatException: For input string: "WirelessRedstone v25.1"
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at java.lang.Double.valueOf(Double.java:504)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at net.licks92.WirelessRedstone.WirelessRedstone.updateCheck(WirelessRedstone.java:425)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at net.licks92.WirelessRedstone.Listeners.WirelessPlayerListener.onPlayerJoin(WirelessPlayerListener.java:30)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at java.lang.reflect.Method.invoke(Method.java:606)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[26-09 15:59:11 ] [Server] [Informatie] [15:59:11 WARN]: at java.lang.Thread.run(Thread.java:745)

**Comment by TMCThomas** [comment]
The same error apears if i create/ remove a sign.

**Comment by Bart-0110** [comment]
Hello Thomas,
Sorry for the inactivity. Try redownloading the plugin, let me know if that works

**Comment by TMCThomas** [comment]
i've forgot to mention that i already downloaded it again. it works now! Thnx for the support :)
