### ISSUE TITLE
SEA_LANTERN error

### ISSUE THREAD

**Issue by pchard** [licks92/WirelessRedstone#130]
Caused by: java.lang.NoSuchFieldError: SEA_LANTERN
        at net.licks92.WirelessRedstone.WireBox.isValidLocation(WireBox.java:574) ~[?:?]
        at net.licks92.WirelessRedstone.WireBox.addWirelessReceiver(WireBox.java:202) ~[?:?]
        at net.licks92.WirelessRedstone.Listeners.WirelessPlayerListener.onPlayerRightClick(WirelessPlayerListener.java:176) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor344.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1492.150]
        ... 15 more

Is it possible to maybe add support for changing the item?
I'm running on kCauldron (modded server - 1.7.10) and I'd love to use this...

**Comment by Bart-0110** [comment]
I'll fix it asap

**Comment by Bart-0110** [comment]
It's fixed! You can test it with the most last dev-build over here:
https://drone.io/github.com/Bart-0110/WirelessRedstone/files
