### ISSUE TITLE
WirelessRedstone Is Running In Game But in console theres nothing about wireless redstone command

### ISSUE THREAD

**Issue by Gaban101** [licks92/WirelessRedstone#145]
[01:14:17] [Thread-27/ERROR]: [WirelessRedstone] dev.bukkit.org rejected the API key provided in plugins/Updater/config.yml
[01:14:17] [Thread-27/ERROR]: [WirelessRedstone] Please double-check your configuration to ensure it is correct.
[01:14:17] [Thread-27/ERROR]: [WirelessRedstone] null
java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.curseforge.com/servermods/files?projectIds=37345
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_73]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_73]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_73]
	at net.gravitydevelopment.updater.Updater.read(Updater.java:643) [WirelessRedstone.jar:?]
	at net.gravitydevelopment.updater.Updater.runUpdater(Updater.java:718) [WirelessRedstone.jar:?]
	at net.gravitydevelopment.updater.Updater.access$100(Updater.java:36) [WirelessRedstone.jar:?]
	at net.gravitydevelopment.updater.Updater$UpdateRunnable.run(Updater.java:713) [WirelessRedstone.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]

**Comment by Bart-0110** [comment]
You can ignore this. This is only for the updater
