### ISSUE TITLE
Getting a few errors

### ISSUE THREAD

**Issue by Nonnisi** [licks92/WirelessRedstone#32]
CraftBukkit version git-Bukkit-1.3.2-R2.0-b2396jnks (MC: 1.3.2)

At startup:
2012-10-29 01:57:44 [INFO] [WirelessRedstone] Enabling WirelessRedstone v1.7b
2012-10-29 01:57:44 [INFO] WirelessRedstone: WirelessRedstone version 1.7b is loading...
2012-10-29 01:57:44 [SEVERE] Error occurred while enabling WirelessRedstone v1.7b (Is it up to date?)
java.lang.NullPointerException
	at net.licks92.WirelessRedstone.Permissions.Vault.setupPermissions(Vault.java:39)
	at net.licks92.WirelessRedstone.Permissions.Vault.<init>(Vault.java:17)
	at net.licks92.WirelessRedstone.Permissions.WirelessPermissions.<init>(WirelessPermissions.java:32)
	at net.licks92.WirelessRedstone.WirelessRedstone.onEnable(WirelessRedstone.java:105)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
	at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:270)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:252)
	at net.minecraft.server.MinecraftServer.i(MinecraftServer.java:298)
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:277)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:227)
	at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:140)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:378)
	at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)

========

When making a transmitter:
2012-10-29 02:04:03 [SEVERE] Could not pass event BlockBreakEvent to WirelessRedstone v1.7b
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
	at net.minecraft.server.ItemInWorldManager.breakBlock(ItemInWorldManager.java:278)
	at net.minecraft.server.ItemInWorldManager.a(ItemInWorldManager.java:205)
	at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:552)
	at net.minecraft.server.Packet14BlockDig.handle(SourceFile:46)
	at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
	at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:111)
	at net.minecraft.server.ServerConnection.b(SourceFile:35)
	at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
	at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:561)
	at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
	at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
	at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
	at net.licks92.WirelessRedstone.Listeners.WirelessBlockListener.onBlockBreak(WirelessBlockListener.java:329)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
	... 16 more

**Comment by Bart-0110** [comment]
Should be fixed now, otherwise create a new issue
