### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Timtower** [licks92/WirelessRedstone#39]
12-12-14 16:21:33 [INFO] [WirelessRedstone] You are using a version that is higher than the repository version! Did you download it on the github code repo?
2012-12-14 16:23:20 [SEVERE] Exception in thread "pool-1-thread-36" 
2012-12-14 16:23:20 [SEVERE] org.apache.commons.lang.UnhandledException: Plugin WirelessRedstone v1.8b generated an exception while executing task 155
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.sqlite.Stmt.executeQuery(Stmt.java:121)
	at net.licks92.WirelessRedstone.Configuration.SQLStorage.getAllChannels(SQLStorage.java:568)
	at net.licks92.WirelessRedstone.Configuration.WirelessConfiguration.getAllChannels(WirelessConfiguration.java:153)
	at net.licks92.WirelessRedstone.WirelessRedstone$2.getValue(WirelessRedstone.java:163)
	at net.licks92.WirelessRedstone.Utils.Metrics.postPlugin(Metrics.java:387)
	at net.licks92.WirelessRedstone.Utils.Metrics.access$5(Metrics.java:354)
	at net.licks92.WirelessRedstone.Utils.Metrics$1.run(Metrics.java:255)
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by Bart-0110** [comment]
Should be fixed now, otherwise create a new issue
